<a href="https://colab.research.google.com/github/Smit-Zaveri/PyTorch/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
#Reshape if we don't know the number of items using -1
my_torch, my_torch1, my_torch2 = torch.arange(10), torch.arange(10), torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch = my_torch.reshape(-1,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
my_torch[1] = 4141
my_torch

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [14]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#grab item
my_torch7[7]

tensor(7)

In [16]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [18]:
#return colum
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])