<a href="https://colab.research.google.com/github/Smit-Zaveri/PyTorch/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor math  operations

In [19]:
import torch
import numpy as np

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [21]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_b - tensor_a
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [24]:
tensor_a * tensor_b
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [25]:
tensor_b / tensor_a
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [26]:
tensor_b % tensor_a
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [27]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [28]:
tensor_a.add(tensor_b)
tensor_b.sub(tensor_a)
tensor_a.mul(tensor_b)
tensor_b.div(tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])